<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'group_574ee37eb9790',
  'title' => 'Lakás adatlap',
  'fields' => array (
    array (
      'key' => 'field_575560c7fd746',
      'label' => 'Főbb adatok',
      'name' => '_copy',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_574ee3d6d53e1',
      'label' => 'Státusz',
      'name' => 'statusz',
      'type' => 'radio',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'free' => 'Szabad',
        'reserved' => 'Foglalt',
        'sold' => 'Eladva',
      ),
      'allow_null' => 0,
      'other_choice' => 0,
      'save_other_choice' => 0,
      'default_value' => 'free',
      'layout' => 'horizontal',
    ),
    array (
      'key' => 'field_5755622f7833a',
      'label' => 'Ár',
      'name' => 'price',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => 'm Ft',
      'min' => '',
      'max' => '',
      'step' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_574ee482d53e2',
      'label' => 'Alapterület',
      'name' => 'alapterulet',
      'type' => 'number',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => 'm<sub>2</sub>',
      'min' => '',
      'max' => '',
      'step' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_575562f77473d',
      'label' => 'Tetőtéri lakás',
      'name' => 'tetoteri',
      'type' => 'true_false',
      'instructions' => 'Pipa ha tetőtéren van',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
    ),
    array (
      'key' => 'field_5755613e1d609',
      'label' => 'Nagyszobák száma',
      'name' => 'nagyszobak',
      'type' => 'number',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => 'm<sub>2</sub>',
      'min' => '',
      'max' => '',
      'step' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_5755617b55030',
      'label' => 'Félszobák száma',
      'name' => 'felszobak',
      'type' => 'number',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => 'm<sub>2</sub>',
      'min' => '',
      'max' => '',
      'step' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_57589eafca090',
      'label' => 'Tájolás',
      'name' => 'tajolas',
      'type' => 'text',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_574ee57911821',
      'label' => 'Helyiségek',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_574ee4afd53e3',
      'label' => 'Közlekedő',
      'name' => 'kozlekedo',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => 'm<sub>2</sub>',
      'min' => '',
      'max' => '',
      'step' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_574ee97d89835',
      'label' => 'WC',
      'name' => 'wc',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => 'm<sub>2</sub>',
      'min' => '',
      'max' => '',
      'step' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_574ee9d3fabe0',
      'label' => 'Fürdőszoba',
      'name' => 'furdoszoba',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => 'm<sub>2</sub>',
      'min' => '',
      'max' => '',
      'step' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_574eeb7de4011',
      'label' => 'Zuhanyzó/Mosdó',
      'name' => 'zuhanyzomosdo',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => 'm<sub>2</sub>',
      'min' => '',
      'max' => '',
      'step' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_574ee9fa7a1e0',
      'label' => 'Konyha',
      'name' => 'konyha',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => 'm<sub>2</sub>',
      'min' => '',
      'max' => '',
      'step' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_574eea4c04820',
      'label' => 'Étkező',
      'name' => 'etkezo',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => 'm<sub>2</sub>',
      'min' => '',
      'max' => '',
      'step' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_574eea65cea07',
      'label' => 'Konyha/Étkező',
      'name' => 'konyhaetkezo',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => 'm<sub>2</sub>',
      'min' => '',
      'max' => '',
      'step' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_574eea833b856',
      'label' => 'Nappali',
      'name' => 'nappali',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => 'm<sub>2</sub>',
      'min' => '',
      'max' => '',
      'step' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_574eeabbfedd0',
      'label' => 'Kamra',
      'name' => 'kamra',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => 'm<sub>2</sub>',
      'min' => '',
      'max' => '',
      'step' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_574eeac8631ea',
      'label' => 'Gardrób',
      'name' => 'gardrob',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => 'm<sub>2</sub>',
      'min' => '',
      'max' => '',
      'step' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_574eeae624e86',
      'label' => 'Szobák',
      'name' => 'szobak',
      'type' => 'repeater',
      'instructions' => 'Szobák felvétele egyesével',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => '',
      'max' => '',
      'layout' => 'table',
      'button_label' => 'Szoba hozzáadása',
      'sub_fields' => array (
        array (
          'key' => 'field_574eeb1124e87',
          'label' => 'Szoba',
          'name' => 'szoba',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => 'm<sub>2</sub>',
          'min' => '',
          'max' => '',
          'step' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
      ),
    ),
    array (
      'key' => 'field_574eed5342980',
      'label' => 'Erkély, terasz',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_574eeca8040dd',
      'label' => 'Erkély',
      'name' => 'erkely',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => 'm<sub>2</sub>',
      'min' => '',
      'max' => '',
      'step' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_574eecbea855d',
      'label' => 'Terasz',
      'name' => 'terasz',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => 'm<sub>2</sub>',
      'min' => '',
      'max' => '',
      'step' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_574eecd0e7d63',
      'label' => 'Loggia',
      'name' => 'loggia',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => 'm<sub>2</sub>',
      'min' => '',
      'max' => '',
      'step' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_574ee62bfcde9',
      'label' => 'Média',
      'name' => 'media',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_574ee64f6a0da',
      'label' => 'Színes alaprajz',
      'name' => 'szines_alaprajz',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'medium_large',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_574ee6ba6a0db',
      'label' => 'Csatolmány',
      'name' => 'csatolmany',
      'type' => 'file',
      'instructions' => 'letölthető pdf',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'library' => 'all',
      'min_size' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_574ee7296a0dc',
      'label' => 'Tömb térkép',
      'name' => 'tomb_terkep',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'medium_large',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_574ee79ecd8d6',
      'label' => 'Lakásválasztó',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_574ee7b1cd8d7',
      'label' => 'Elhelyezkedés a szinten',
      'name' => 'svg_on_floor',
      'type' => 'textarea',
      'instructions' => 'SVG path required.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => '',
      'new_lines' => 'wpautop',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_57589b0d97e32',
      'label' => 'Kapcsolódó',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_57589b2997e33',
      'label' => 'Hasonló lakások',
      'name' => 'hasonlo_lakasok',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'lakas',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 1,
      'multiple' => 1,
      'return_format' => 'object',
      'ui' => 1,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'lakas',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_57509292051e8',
  'title' => 'Tömb épület és lakás',
  'fields' => array (
    array (
      'key' => 'field_575092f80e76f',
      'label' => 'Nézeti kép',
      'name' => 'nezeti_kep',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'medium_large',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_575093327e244',
      'label' => 'SVG',
      'name' => 'svg_data',
      'type' => 'textarea',
      'instructions' => 'Pozíciója a szülő nézeti képén',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => '',
      'new_lines' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'taxonomy',
        'operator' => '==',
        'value' => 'blokk',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

endif;